#!/bin/bash

# $1 variable name
# $2 message if variable is empty or unset
function check_variable {
  if [ -z "${!1}" ]; then
    echo "$2: $1"
    exit 1
  fi
}

root=$(pwd)
BUILDDIR=.ninja-build
PATH=${root}/${builddir}/bin:${root}/builder/bin:${PATH}


# load env vars

. my-config
. ./builder/build-env

# User config

check_variable PROJECT "project name not set"
check_variable BASENAME "base path for docker image name not set"
check_variable WEBPORT "port for application web server not set"
check_variable DBADMINPORT "port for phpmyadmin web server not set"
check_variable MYSQL_DATABASE "MariaDB database not set"
check_variable MYSQL_USER "MariaDB username not set"
check_variable MYSQL_PASSWORD "MariaDB password not set"

export PROJECT
export BASENAME
export WEBPORT
export DBADMINPORT
export MYSQL_DATABASE
export MYSQL_USER
export MYSQL_PASSWORD
export MYSQL_ROOT_PASSWORD

# Builder config

SRC_DIR=${root}/src

export _UID
export _GID
export SRC_DIR
export BUILDDIR

DB_IMAGE=mariadb:10.1
DB_ADMIN_IMAGE=nazarpc/phpmyadmin
VOLUME_IMAGE=busybox
COMPOSER_IMAGE=frma/baseimage-composer

export DB_IMAGE
export DB_ADMIN_IMAGE
export VOLUME_IMAGE
export COMPOSER_IMAGE

ninja_build=build.ninja

if [ ! -f ${ninja_build} ]; then
  python configure.py
fi

ninja -C ${root} -j 1 $@
