web:
  image: {{IMGBASE}}/{{PROJECT}}-web
  container_name: {{PROJECT}}-web
  volumes_from:
  - {{PROJECT}}-src
  ports:
  - "{{DEVPORT}}:8080"

db:
  image: mariadb:10.1
  container_name: {{PROJECT}}-db
  volumes_from:
  - {{PROJECT}}-db-volume
