web:
  image: "${BASENAME}/${PROJECT}-web"
  volumes:
  - "${SRC_DIR}:/home/devuser/src"
  ports:
  - "${WEBPORT}:8080"
  links:
  - db:db
  working_dir: "/home/devuser/src/${PROJECT}"

db:
  image: ${DB_IMAGE}
  volumes_from:
  - db-volume
  environment:
    TERM: dumb

db-admin:
  image: ${DB_ADMIN_IMAGE}
  links:
  - db:mysql
  ports:
  - "${DBADMINPORT}:80"
